---
output: github_document
---
<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# DSFworld


## Overview

DSFworld is a web application and set of supporting scripts for the analysis and interactive modeling of Differential Scanning Fluorimetry data. The full DSFworld web application can be access at the url: https://gestwickilab.shinyapps.io/dsfworld/.

This repository contains the full code for the DSFworld web application, as well as the associated scripts, and modularized mini web application for each of the individual tasks handled at DSFworld (uploading, layouts, plotting, analysis, and downloads.)

The DSFworld website is presented as a part of a larger publication entitled "Three Essential Resources to Improve Differential Scanning Flourimetry (DSF) Experiments". The full text of this paper and its supplementary information can be downloaded from the DSFworld website, as well as from the 0_full_app folder of this repository. 


## Usage
DSFworld and the associated scripts use the following packages:

* [shiny](https://shiny.rstudio.com/), for building a web interface.
* [shinyBS](https://cran.r-project.org/web/packages/shinyBS/shinyBS.pdf), for drop-down panels.
* [shinyalert](https://cran.r-project.org/web/packages/shinyalert/shinyalert.pdf), for pop-up messages.
* [shinycssloaders](https://cran.r-project.org/web/packages/shinycssloaders/shinycssloaders.pdf), for busy spinners.
* [rhandsontable](https://cran.r-project.org/web/packages/rhandsontable/rhandsontable.pdf), for editable tables.

* [tidvyerse](https://www.tidyverse.org/), for data handling and visualization.
* [modelr](https://cran.r-project.org/web/packages/modelr/modelr.pdf), for data and model handling.
* [minpack.lm](https://cran.r-project.org/web/packages/minpack.lm/minpack.lm.pdf), for fitting.
* [signal](https://cran.r-project.org/web/packages/signal/signal.pdf), for Savitsky-Golay filtering.
* [quantmod](https://cran.r-project.org/web/packages/quantmod/quantmod.pdf), for assistance starting parameter estimates.
* [SciViews](https://cran.r-project.org/web/packages/SciViews/SciViews.pdf), for natural logarithms.


## Contact
You can contact us at dsfworlducsf (at) gmail (dot) com.
